# Generated by Django 5.0.8 on 2024-08-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="description",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
