# Generated by Django 5.0.8 on 2024-08-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_alter_car_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("Coupe", "Coupe"),
                    ("Cabriolet", "Cabriolet"),
                    ("Sedan", "Sedan"),
                    ("SUV", "Suv"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
