# Generated by Django 5.0.8 on 2024-08-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_remove_car_odometer_remove_car_price_carline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carline",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
