# Generated by Django 5.0.8 on 2024-08-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0006_alter_carline_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carline",
            old_name="is_active",
            new_name="is_published",
        ),
        migrations.RemoveField(
            model_name="car",
            name="is_published",
        ),
    ]
