# Generated by Django 5.0.8 on 2024-08-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0007_rename_is_active_carline_is_published_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CarLine",
            new_name="CarInstance",
        ),
        migrations.AlterModelOptions(
            name="carinstance",
            options={"verbose_name": "CarInstance"},
        ),
    ]
