# Generated by Django 5.0.8 on 2024-08-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0008_rename_carline_carinstance_alter_carinstance_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="description",
        ),
        migrations.RemoveField(
            model_name="car",
            name="time_created",
        ),
        migrations.RemoveField(
            model_name="car",
            name="time_updated",
        ),
        migrations.RemoveField(
            model_name="car",
            name="year",
        ),
        migrations.AddField(
            model_name="carinstance",
            name="description",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="carinstance",
            name="year",
            field=models.PositiveIntegerField(default="1970"),
        ),
    ]
