# Generated by Django 5.0.8 on 2024-08-21 12:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0009_remove_car_description_remove_car_time_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carinstance",
            name="time_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="carinstance",
            name="time_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
