# Generated by Django 5.0.8 on 2024-08-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0010_carinstance_time_created_carinstance_time_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="slug",
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
