# Generated by Django 5.0.8 on 2024-08-22 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0011_car_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="slug",
        ),
    ]
