# Generated by Django 5.0.8 on 2024-08-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0012_remove_car_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="slug",
            field=models.SlugField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
