# Generated by Django 5.0.8 on 2024-08-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0013_car_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="carinstance",
            name="sku",
        ),
    ]
