# Generated by Django 5.0.8 on 2024-08-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0014_remove_car_slug_remove_carinstance_sku"),
    ]

    operations = [
        migrations.RenameField(
            model_name="brand",
            old_name="name",
            new_name="brand_name",
        ),
        migrations.RenameField(
            model_name="car",
            old_name="make",
            new_name="brand",
        ),
    ]
