# Generated by Django 5.0.8 on 2024-08-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0015_rename_name_brand_brand_name_rename_make_car_brand"),
    ]

    operations = [
        migrations.RenameField(
            model_name="brand",
            old_name="brand_name",
            new_name="brand",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="category_name",
        ),
    ]
