services:
  backend:
    build: .
    container_name: dd
#    command: /bin/bash python manage.py runserver 0.0.0.0:8000
    command: /bin/bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app